# Generated by Django 2.2.6 on 2019-10-13 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_auto_20191012_2257'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
