# Generated by Django 2.2.6 on 2019-10-13 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminApp', '0003_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('afiliacao', models.CharField(max_length=200)),
                ('departamento', models.CharField(max_length=200)),
                ('formacao', models.CharField(max_length=200)),
                ('linkLates', models.CharField(max_length=300)),
            ],
        ),
    ]
